# -*- coding: utf-8 -*-
"""Crop lens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZQ7_nYK-4h7PdOFNXft5Hq9k-r5lDgA
"""

from google.colab import drive
drive.mount('/content/drive')

import os

print(os.listdir("/content/drive/MyDrive"))

import os

flower_path = "/content/drive/MyDrive/Croplens"

for item in os.listdir(flower_path):
    print(item)

import os

base_path = "/content/drive/MyDrive/Croplens"

print("Inside Flower:")
print(os.listdir(base_path))

print("\nCroplens:")
print(os.listdir(os.path.join(base_path, "Dataset")))

import os

base_path = "/content/drive/MyDrive/Croplens"

image_files = []

for root, dirs, files in os.walk(base_path):
    for file in files:
        if file.lower().endswith(('.jpg', '.jpeg', '.png', '.webp')):
            image_files.append(os.path.join(root, file))

print("Total images found:", len(image_files))
print("Sample:", image_files[:5])

dataset_path = "/content/drive/MyDrive/Croplens/Dataset"

base_path = "/content/drive/MyDrive/Croplens/Dataset"

!pip install tensorflow

import os

base_path = "/content/drive/MyDrive/Croplens/Dataset"

class_counts = {}
total = 0

for root, dirs, files in os.walk(base_path):
    # detect image files in each folder
    images = [f for f in files if f.lower().endswith(('.jpg','.jpeg','.png'))]

    if len(images) > 0:
        class_name = os.path.basename(root)
        class_counts[class_name] = class_counts.get(class_name, 0) + len(images)
        total += len(images)

print("Total images found:", total)
print("\nSample class counts:")
for k,v in list(class_counts.items())[:10]:
    print(k, ":", v)

import tensorflow as tf

dataset_base_path = "/content/drive/MyDrive/Croplens/Dataset"

# Define a validation split ratio (e.g., 20% for validation)
validation_split_ratio = 0.2
seed_value = 123 # For reproducibility

train_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_base_path,
    validation_split=validation_split_ratio,
    subset="training",
    seed=seed_value,
    image_size=(224,224),
    batch_size=32
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_base_path,
    validation_split=validation_split_ratio,
    subset="validation",
    seed=seed_value,
    image_size=(224,224),
    batch_size=32
)

"""**Data Preprocessing**"""

!pip install ultralytics
!pip install tensorflow scikit-learn seaborn

import tensorflow as tf
import math

IMG_SIZE = (224,224)
BATCH_SIZE = 32
seed_value = 123 # For reproducibility

dataset_base_path = "/content/drive/MyDrive/Croplens/Dataset"

# Get class names and total number of images by loading the dataset temporarily
# without batching to easily count.
temp_ds_for_info = tf.keras.utils.image_dataset_from_directory(
    dataset_base_path,
    image_size=IMG_SIZE,
    batch_size=None, # Load as individual samples to get total count easily
    shuffle=False # Order doesn't matter for counting
)

class_names = temp_ds_for_info.class_names
NUM_CLASSES = len(class_names)
total_images = tf.data.experimental.cardinality(temp_ds_for_info).numpy()

# Now load the dataset to be split, ensuring it's shuffled for random distribution
# and unbatched so that take/skip work on individual samples.
shuffled_unbatched_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_base_path,
    image_size=IMG_SIZE,
    batch_size=None, # Load as individual samples
    shuffle=True, # Shuffle for random split
    seed=seed_value
)

# Define split ratios
TRAIN_RATIO = 0.7
VALIDATION_RATIO = 0.15
TEST_RATIO = 0.15

# Calculate number of samples for each split
train_size = math.floor(total_images * TRAIN_RATIO)
val_size = math.floor(total_images * VALIDATION_RATIO)
test_size = total_images - train_size - val_size # Assign remaining to test to ensure sum matches total

# Create train_ds, val_ds, test_ds
train_ds = shuffled_unbatched_ds.take(train_size).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
remaining_after_train = shuffled_unbatched_ds.skip(train_size)

val_ds = remaining_after_train.take(val_size).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
test_ds = remaining_after_train.skip(val_size).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

print(f"Total images: {total_images}")
print(f"Number of classes: {NUM_CLASSES}")
print(f"Class names: {class_names}")
print(f"Train images: {train_size}")
print(f"Validation images: {val_size}")
print(f"Test images: {test_size}")

"""**EfficientNetB0**"""

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras import layers, models

base_model = EfficientNetB0(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable = False

efficientnet = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(NUM_CLASSES, activation='softmax')
])

efficientnet.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

hist_eff = efficientnet.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

"""**ResNet50**"""

from tensorflow.keras.applications import ResNet50

base_model = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable = False

resnet = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(NUM_CLASSES, activation='softmax')
])

resnet.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

hist_res = resnet.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

"""**MobileNetV2**"""

from tensorflow.keras.applications import MobileNetV2

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable = False

mobilenet = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(NUM_CLASSES, activation='softmax')
])

mobilenet.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

hist_mobile = mobilenet.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

"""**YOLOv8 Classification**

Train
"""

from ultralytics import YOLO

model = YOLO("yolov8n-cls.pt")

results = model.train(
    data="/content/dataset",
    epochs=10,
    imgsz=224
)

"""Validate:"""

metrics = model.val()
print(metrics.top1)
print(metrics.top5)

"""**Confusion Matrix Function**"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

def plot_confusion_matrix(model, test_ds, class_names):

    y_true = np.concatenate(
        [y.numpy() for x,y in test_ds]
    )

    y_pred = np.argmax(
        model.predict(test_ds),
        axis=1
    )

    cm = confusion_matrix(y_true, y_pred)

    plt.figure(figsize=(10,8))
    sns.heatmap(
        cm,
        annot=True,
        fmt='d',
        xticklabels=class_names,
        yticklabels=class_names
    )
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

plot_confusion_matrix(
    efficientnet,
    test_ds,
    class_names
)

"""**Accuracy Graph**"""

import matplotlib.pyplot as plt

def plot_accuracy(history, title):

    plt.figure(figsize=(8,5))

    plt.plot(
        history.history['accuracy'],
        label='Train'
    )

    plt.plot(
        history.history['val_accuracy'],
        label='Validation'
    )

    plt.title(title)
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.show()

plot_accuracy(hist_eff, "EfficientNet")
plot_accuracy(hist_res, "ResNet50")
plot_accuracy(hist_mobile, "MobileNetV2")